### ISSUE TITLE
Build: 1 failed, how to fix this

### ISSUE THREAD

**Issue by iamjosave14202** [NotNanook/Ascendit-Raot#4]
fatal error LNK1120: 5 unresolved externals
![image](https://user-images.githubusercontent.com/55599699/235867319-646875a8-795e-46f0-8d2f-b70a16791b9a.png)

**Comment by DarkManus** [comment]
I have the same issue. Rqmaot posted detailed instructions on how to build the .dll in Visual Studio, but I keep getting the same errors whenever I try. Sorry if I come off as ignorant, but a little help would be appreciated.
![Capture](https://user-images.githubusercontent.com/121848886/236719203-ec90e54e-07ad-4ac5-a915-9375121b73e5.PNG)

**Comment by NotNanook** [comment]
Well you can just install the missing package with winget

**Comment by NotNanook** [comment]
the newest version has the issue fixed
